# Generated by Django 3.0.6 on 2020-05-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200513_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='has_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='has_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
