# Generated by Django 3.0.6 on 2020-05-12 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200513_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=400)),
                ('timestamp', models.DateField(auto_now=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('featured', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Author')),
                ('category', models.ManyToManyField(to='news.Category')),
            ],
        ),
    ]
