# Generated by Django 3.0.6 on 2020-05-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200513_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='overview',
            field=models.CharField(max_length=1000),
        ),
    ]
