# Generated by Django 3.0.6 on 2020-05-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200515_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='web_name',
            field=models.CharField(max_length=50),
        ),
    ]
