# Generated by Django 3.0.6 on 2020-05-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200513_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='featured',
        ),
    ]
