# Generated by Django 3.0.6 on 2020-05-17 21:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200515_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Webs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_name', models.CharField(max_length=50)),
                ('web_content', tinymce.models.HTMLField(blank=True, null=True)),
                ('pictures', models.ManyToManyField(blank=True, to='news.Pictures')),
                ('web_filles', models.ManyToManyField(blank=True, to='news.Files')),
            ],
        ),
        migrations.CreateModel(
            name='AllWebs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_title', models.CharField(max_length=50)),
                ('pictures', models.ManyToManyField(blank=True, to='news.Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='AllFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_files_name', models.CharField(max_length=50)),
                ('files', models.ManyToManyField(blank=True, to='news.Files')),
            ],
        ),
    ]
