# Generated by Django 3.0.6 on 2020-05-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_news_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='has_own_web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='has_own_web',
            field=models.BooleanField(default=False),
        ),
    ]
