# Generated by Django 3.0.6 on 2020-05-13 00:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200513_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainnews',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
