# Generated by Django 3.0.6 on 2020-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_allfiles_allwebs_files_webs'),
    ]

    operations = [
        migrations.AddField(
            model_name='allfiles',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='allwebs',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='files',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pictures',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webs',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
