# Generated by Django 3.0.6 on 2020-05-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200518_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='overview',
            field=models.CharField(default='Nie posiada opisu', max_length=1000),
        ),
    ]
