# Generated by Django 3.0.6 on 2020-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_pictures_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='overview',
        ),
        migrations.AddField(
            model_name='gallery',
            name='overview',
            field=models.CharField(default='Nie posiada opisu', max_length=1000),
        ),
    ]
