# Generated by Django 3.0.6 on 2020-05-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20200518_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(to='news.Pictures'),
        ),
    ]
