# Generated by Django 3.0.6 on 2020-05-18 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20200518_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='has_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
