# Generated by Django 3.0.6 on 2020-05-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20200518_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='current_pictures',
            field=models.ManyToManyField(related_name='current', to='news.Pictures'),
        ),
    ]
