# Generated by Django 3.0.6 on 2020-05-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_gallery_current_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='current_pictures',
        ),
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.ManyToManyField(blank=True, to='news.Category'),
        ),
    ]
