# Generated by Django 3.0.6 on 2020-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20200520_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='to_gallery',
            field=models.BooleanField(default=False),
        ),
    ]
