# Generated by Django 3.0.6 on 2020-05-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_pictures_to_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allwebs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='allwebs',
            name='pictures',
        ),
        migrations.DeleteModel(
            name='AllFiles',
        ),
        migrations.DeleteModel(
            name='AllWebs',
        ),
    ]
