# Generated by Django 3.0.6 on 2020-05-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20200522_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
