# Generated by Django 3.0.6 on 2020-05-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20200522_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webs',
            name='web_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
