# Generated by Django 3.0.6 on 2020-05-22 19:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20200522_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webs',
            name='web_content',
            field=tinymce.models.HTMLField(),
        ),
    ]
