# Generated by Django 3.0.6 on 2020-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0027_auto_20200522_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cat_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
