# Generated by Django 3.0.6 on 2020-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_author_cat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='cat_text_color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
