# Generated by Django 3.0.6 on 2020-05-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_author_cat_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='cat_color',
            field=models.TextField(default='#007bff'),
        ),
        migrations.AlterField(
            model_name='author',
            name='cat_text_color',
            field=models.TextField(default='#FFFFFF'),
        ),
    ]
