# Generated by Django 3.0.6 on 2020-05-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_webcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcategory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
