# Generated by Django 3.0.6 on 2020-05-22 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_webcategory_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcategory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.Author'),
        ),
    ]
