# Generated by Django 3.0.6 on 2020-05-24 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_webcategory_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
