# Generated by Django 3.0.6 on 2020-05-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0037_auto_20200526_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
