# Generated by Django 3.0.6 on 2020-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0040_auto_20200526_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='overview',
            field=models.TextField(max_length=1000),
        ),
    ]
