# Generated by Django 3.0.6 on 2020-05-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0041_auto_20200531_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='images_in',
            field=models.TextField(blank=True, null=True),
        ),
    ]
