# Generated by Django 3.0.6 on 2020-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0042_pictures_images_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='web_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='web_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
