# Generated by Django 3.0.6 on 2020-05-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0043_auto_20200601_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='overview',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='mainnews',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='overview',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
