# Generated by Django 3.0.6 on 2020-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0017_auto_20200519_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_new', models.BooleanField(default=False)),
                ('edit_main', models.BooleanField(default=False)),
                ('adding_images', models.BooleanField(default=False)),
                ('create_gallery', models.BooleanField(default=False)),
                ('create_files', models.BooleanField(default=False)),
                ('create_webs', models.BooleanField(default=False)),
                ('cat', models.ManyToManyField(to='news.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Rangs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.ManyToManyField(to='auth_user.Permissions')),
            ],
        ),
    ]
