# Generated by Django 3.0.6 on 2020-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='create_user',
            field=models.BooleanField(default=False),
        ),
    ]
