# Generated by Django 3.0.6 on 2020-05-22 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0002_permissions_create_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='cat',
        ),
    ]
