# Generated by Django 3.0.6 on 2020-05-22 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0004_permissions_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangs',
            name='permissions',
        ),
        migrations.AddField(
            model_name='rangs',
            name='permissions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_user.Permissions'),
        ),
    ]
