# Generated by Django 3.0.6 on 2020-05-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0005_auto_20200522_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangs',
            name='permissions',
        ),
        migrations.AddField(
            model_name='rangs',
            name='adding_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='create_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='create_gallery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='create_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='create_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='create_webs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rangs',
            name='edit_main',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
    ]
