# Generated by Django 3.0.6 on 2020-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0008_rangs_write_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
